<?php
/** @var \Quantilus\MobiusUser\Block\MobiususerOptions $block */
    
$userData = $block->getUserData();
?>
<div class="mobius-user">
    <h1><?= $block->escapeHtml($block->getName()) ?></h1>
    <div class="content-wrapper">
        <div class="useractions">
            <div class="action-option kitcode">
                <h2>I have a Kit Code</h2>
                <form action="<?= $block->escapeUrl($block->getProcessKitCodeUrl()) ?>" method="post">
                    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
                    <input type="text" name="kitcode" id="kitcode" placeholder="Enter your Kit Code" required />
                    <button type="submit">Submit</button>
                </form>
            </div>
            <div class="action-option purchase">
                <h2>I want to purchase a Kit.</h2>
                <p>If you have a Voucher Code, enter it below, otherwise just click Proceed</p>
                <form action="<?= $block->escapeUrl($block->getPurchaseKitUrl()) ?>" method="post">
                    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
                    <input type="text" name="voucher_code" id="voucher_code" placeholder="Enter your Voucher Code" />
                    <button type="submit">Proceed</button>
                </form>
            </div>
            <div class="action-option view-order">
                <h2>I want to view my orders</h2>
                <form action="<?= $block->escapeUrl($block->getViewMyOrdersUrl()) ?>" method="post">
                    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
                    <input type="text" name="accountnumber" id="accountnumber" value="<?= $userData['accountnumber'] ?>" placeholder="Enter your Account Number" required />
                    <input type="text" name="email" id="email" value="<?= $userData['email'] ?>" placeholder="Enter your Email" required />
                    <button type="submit">View My Orders</button>
                </form>
            </div>
        </div>
    </div>
</div>